export const createEnsTable = `
CREATE TABLE IF NOT EXISTS ens (
  ID SERIAL PRIMARY KEY NOT NULL UNIQUE,
  ENS_ID VARCHAR(255) NOT NULL UNIQUE,
  NAME VARCHAR(255) NOT NULL UNIQUE,
  ADDRESS VARCHAR(42) NOT NULL,
  CREATED_AT timestamp NOT NULL DEFAULT now(),
  SMS_SID VARCHAR(34) UNIQUE
);
`

export const insertEnsTable = `
INSERT INTO ens (ENS_ID, NAME, ADDRESS) 
    VALUES %L 
    ON CONFLICT DO NOTHING 
    RETURNING *
`

export const updateEnsSmsSid = `
UPDATE ens
SET sms_sid = $1
WHERE id = $2
RETURNING *
`